
version: '3.4'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: drf
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
      MYSQL_ROOT_PASSWORD: passwd
    ports:
      - '3366:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
 
  drf-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - "BUILD_ENV"
    ports:
      - "8000:8000"
    volumes:
      - "./:/usr/api"
    depends_on: ['mysql', 'prometheus']

volumes:
  db:
