
version: '3.4'
services:
  prometheus:
    image: prom/prometheus:v2.14.0
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:6.5.2
    restart: always
    ports:
      - 3060:3000
    depends_on: ['prometheus']

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: drf
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
      MYSQL_ROOT_PASSWORD: passwd
    ports:
      - '3366:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
 
  drf-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - "BUILD_ENV"
    ports:
      - "8000:8000"
    volumes:
      - "./:/usr/api"
    depends_on: ['mysql', 'prometheus']

volumes:
  db:
