
version: '3'
services:
    api:
      build:
        context: .
        dockerfile: Dockerfile
        args:
          - "BUILD_ENV"
      ports:
        - "8000:8000"
      volumes:
        - "./:/usr/api"
