global:
    scrape_interval: 10s
    evaluation_interval: 10s

rule_files:
  - "django.rules"

scrape_configs:
    - job_name: monitoring
      static_configs:
        - targets:
            - localhost:9090

    - job_name: django
      static_configs:
        - targets: 
            - drf-api:8000
